apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoBuild
metadata:
  name: travels
spec:
  type: RemoteSource
  gitSource:
    contextDir: bamoe
    uri: "https://github.com/NikitaPorwal21/bamoe/"
  # set your maven nexus repository to speed up the build time
  #mavenMirrorURL:
---
apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  name: bamoe
spec:
  infinispan:
    useKogitoInfra: true
  kafka:
    useKogitoInfra: true